[project]
name = "esiosapy"
version = "0.0.1"
description = "Unofficial ESIOS API Python library. Up to date and fully equipped."
authors = [{ name = "M4RC0Sx" }]
requires-python = ">=3.9,<4"
readme = "README.md"
license = "GPL-3.0-or-later"
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
]
dependencies = [
    "pydantic>=2.12.5",
    "requests>=2.32.5",
]

[dependency-groups]
dev = ["mypy>=1.19.1", "ruff>=0.15.0", "types-requests>=2.32.4.20260107"]
test = ["pytest>=8.4.2", "pytest-mock>=3.15.1"]

[tool.uv]
default-groups = ["dev", "test"]

[tool.uv.build-backend]
module-name = ["esiosapy"]
module-root = ""

[build-system]
requires = ["uv_build>=0.9.30,<0.10.0"]
build-backend = "uv_build"

[tool.ruff.lint]
select = [
    # pycodestyle
    "E",
    # Pyflakes
    "F",
    # pyupgrade
    "UP",
    # flake8-bugbear
    "B",
    # flake8-simplify
    "SIM",
    # isort
    "I",
]

[tool.mypy]
strict = true
plugins = ["pydantic.mypy"]

warn_redundant_casts = true
warn_unused_ignores = true
disallow_any_generics = true
check_untyped_defs = true
no_implicit_reexport = true

# for strict mypy
disallow_untyped_defs = true

[tool.pydantic-mypy]
init_forbid_extra = true
init_typed = true
warn_required_dynamic_aliases = true

[tool.pytest.ini_options]
testpaths = ["tests"]
