name: release
on:
    push:
        branches:
        - master

jobs:
    release:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            #----------------------------------------------
            #       Check-out repo
            #----------------------------------------------
            - name: Checkout
              uses: actions/checkout@v4
              with:
                fetch-depth: 0

            #----------------------------------------------
            #       Install Node.js and Semantic Release
            #----------------------------------------------
            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                node-version: '20.16.0'
            - name: Install Semantic Release
              run: npm install -g semantic-release@24.1.0 @semantic-release/git@10.0.1 @semantic-release/changelog@6.0.3 conventional-changelog-conventionalcommits@8.0.0 semantic-release-replace-plugin@1.2.7

            #----------------------------------------------
            #       Install uv
            #----------------------------------------------
            - name: Install uv
              uses: astral-sh/setup-uv@v5
              with:
                enable-cache: true

            #----------------------------------------------
            #       Install Python dependencies
            #----------------------------------------------
            - name: Install dependencies
              run: uv sync --frozen

            #----------------------------------------------
            #       Semantic Release
            #----------------------------------------------
            - name: Semantic Release
              run: npx semantic-release
              env:
                GH_TOKEN: ${{ secrets.GH_TOKEN }}

            #----------------------------------------------
            #       Build and publish package
            #----------------------------------------------
            - name: Build and publish package
              run: |
                uv build
                uv publish
              env:
                UV_PUBLISH_TOKEN: ${{ secrets.PYPI_TOKEN }}
            