name: test
on:
    push:
      branches:
        - develop
    pull_request:
      types:
        - opened
        - synchronize

jobs:
    run-tests:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            #----------------------------------------------
            #       Check-out repo
            #----------------------------------------------
            - name: Checkout
              uses: actions/checkout@v4
              with:
                fetch-depth: 0

            #----------------------------------------------
            #       Install uv
            #----------------------------------------------
            - name: Install uv
              uses: astral-sh/setup-uv@v5
              with:
                enable-cache: true

            #----------------------------------------------
            #       Install dependencies
            #----------------------------------------------
            - name: Install dependencies
              run: uv sync --frozen

            #----------------------------------------------
            #       Run linting checks
            #----------------------------------------------
            - name: Run linting checks
              run: uv run ruff check

            #----------------------------------------------
            #       Run tests
            #----------------------------------------------
            - name: Run tests
              run: uv run pytest
            